export type ApiKeyStatus = 'active' | 'blocked'

export interface ApiKey {
  id: string
  provider: string
  providerIcon: string
  name: string
  keyMasked: string
  model: string
  status: ApiKeyStatus
  limitPerMonth: number
  usage: number
  usagePercent: number
  resetInDays: number | null
  createdAt: string
  createdTime: string
}

const API_KEYS: ApiKey[] = [
  {
    id: '1',
    provider: 'OpenAI',
    providerIcon: '🟢',
    name: 'OpenAI - Primary',
    keyMasked: 'sk-oai-**********1b2',
    model: 'GPT-4o',
    status: 'active',
    limitPerMonth: 200,
    usage: 128.45,
    usagePercent: 64.2,
    resetInDays: 12,
    createdAt: '01 Mei 2025',
    createdTime: '10:30',
  },
  {
    id: '2',
    provider: 'Anthropic',
    providerIcon: '🟠',
    name: 'Anthropic - Main',
    keyMasked: 'sk-ant-**********3d4',
    model: 'Claude 3.5 Sonnet',
    status: 'active',
    limitPerMonth: 150,
    usage: 87.6,
    usagePercent: 58.4,
    resetInDays: 12,
    createdAt: '05 Mei 2025',
    createdTime: '14:20',
  },
  {
    id: '3',
    provider: 'Google',
    providerIcon: '🔵',
    name: 'Google - Gemini Pro',
    keyMasked: 'AIza-**********5f6',
    model: 'Gemini 1.5 Pro',
    status: 'active',
    limitPerMonth: 100,
    usage: 45.2,
    usagePercent: 45.2,
    resetInDays: 18,
    createdAt: '10 Mei 2025',
    createdTime: '09:15',
  },
  {
    id: '4',
    provider: 'Azure',
    providerIcon: '🔷',
    name: 'Azure OpenAI',
    keyMasked: 'sk-az-**********7h8',
    model: 'GPT-4 Turbo',
    status: 'active',
    limitPerMonth: 300,
    usage: 210.3,
    usagePercent: 70.1,
    resetInDays: 22,
    createdAt: '15 Mei 2025',
    createdTime: '11:05',
  },
  {
    id: '5',
    provider: 'Mistral',
    providerIcon: '🟡',
    name: 'Mistral - Mixtral',
    keyMasked: 'sk-mis-**********9i0',
    model: 'Mixtral 8x22B',
    status: 'active',
    limitPerMonth: 80,
    usage: 22.75,
    usagePercent: 28.4,
    resetInDays: 5,
    createdAt: '20 Mei 2025',
    createdTime: '13:10',
  },
  {
    id: '6',
    provider: 'Cohere',
    providerIcon: '⚫',
    name: 'Cohere - Command R+',
    keyMasked: 'sk-coh-**********1k2',
    model: 'Command R+',
    status: 'blocked',
    limitPerMonth: 50,
    usage: 50.0,
    usagePercent: 100.0,
    resetInDays: null,
    createdAt: '22 Mei 2025',
    createdTime: '08:30',
  },
  {
    id: '7',
    provider: 'Perplexity',
    providerIcon: '🟣',
    name: 'Perplexity - Sonar',
    keyMasked: 'pplx-**********3m4',
    model: 'Sonar Large',
    status: 'active',
    limitPerMonth: 60,
    usage: 18.1,
    usagePercent: 30.2,
    resetInDays: 9,
    createdAt: '25 Mei 2025',
    createdTime: '15:00',
  },
  {
    id: '8',
    provider: 'OpenAI',
    providerIcon: '🟢',
    name: 'OpenAI - Backup',
    keyMasked: 'sk-oai-**********5p6',
    model: 'GPT-3.5 Turbo',
    status: 'blocked',
    limitPerMonth: 40,
    usage: 40.0,
    usagePercent: 100.0,
    resetInDays: null,
    createdAt: '26 Mei 2025',
    createdTime: '10:00',
  },
  {
    id: '9',
    provider: 'Groq',
    providerIcon: '🔴',
    name: 'Groq - Llama',
    keyMasked: 'gsk-**********7q8',
    model: 'Llama 3 70B',
    status: 'active',
    limitPerMonth: 120,
    usage: 45.8,
    usagePercent: 38.2,
    resetInDays: 15,
    createdAt: '28 Mei 2025',
    createdTime: '09:45',
  },
  {
    id: '10',
    provider: 'Together',
    providerIcon: '🟤',
    name: 'Together AI',
    keyMasked: 'sk-tog-**********9r0',
    model: 'Llama 3.1 405B',
    status: 'active',
    limitPerMonth: 90,
    usage: 32.15,
    usagePercent: 35.7,
    resetInDays: 20,
    createdAt: '30 Mei 2025',
    createdTime: '11:20',
  },
  {
    id: '11',
    provider: 'OpenRouter',
    providerIcon: '⚪',
    name: 'OpenRouter - Multi',
    keyMasked: 'sk-or-**********1s2',
    model: 'Claude 3 Opus',
    status: 'active',
    limitPerMonth: 250,
    usage: 95.4,
    usagePercent: 38.2,
    resetInDays: 8,
    createdAt: '01 Jun 2025',
    createdTime: '08:00',
  },
  {
    id: '12',
    provider: 'DeepSeek',
    providerIcon: '🔵',
    name: 'DeepSeek - V3',
    keyMasked: 'sk-dsk-**********3t4',
    model: 'DeepSeek V3',
    status: 'active',
    limitPerMonth: 75,
    usage: 28.5,
    usagePercent: 38.0,
    resetInDays: 14,
    createdAt: '03 Jun 2025',
    createdTime: '14:30',
  },
  {
    id: '13',
    provider: 'Replicate',
    providerIcon: '🟣',
    name: 'Replicate - Flux',
    keyMasked: 'r8_**********5u6',
    model: 'Flux Pro',
    status: 'blocked',
    limitPerMonth: 30,
    usage: 30.0,
    usagePercent: 100.0,
    resetInDays: null,
    createdAt: '05 Jun 2025',
    createdTime: '16:40',
  },
  {
    id: '14',
    provider: 'Fireworks',
    providerIcon: '🟠',
    name: 'Fireworks - Fast',
    keyMasked: 'fw-**********7v8',
    model: 'Mixtral 8x7B',
    status: 'active',
    limitPerMonth: 55,
    usage: 12.3,
    usagePercent: 22.4,
    resetInDays: 25,
    createdAt: '08 Jun 2025',
    createdTime: '10:15',
  },
  {
    id: '15',
    provider: 'AI21',
    providerIcon: '🟢',
    name: 'AI21 - Jurassic',
    keyMasked: 'sk-ai21-**********9w0',
    model: 'Jurassic 2 Ultra',
    status: 'active',
    limitPerMonth: 45,
    usage: 8.75,
    usagePercent: 19.4,
    resetInDays: 28,
    createdAt: '10 Jun 2025',
    createdTime: '09:00',
  },
  {
    id: '16',
    provider: 'Cohere',
    providerIcon: '⚫',
    name: 'Cohere - Embed',
    keyMasked: 'sk-coh-**********1x2',
    model: 'Embed English v3',
    status: 'active',
    limitPerMonth: 35,
    usage: 15.2,
    usagePercent: 43.4,
    resetInDays: 11,
    createdAt: '12 Jun 2025',
    createdTime: '13:45',
  },
  {
    id: '17',
    provider: 'Poe',
    providerIcon: '🔴',
    name: 'Poe - API',
    keyMasked: 'poe-**********3y4',
    model: 'GPT-4o Mini',
    status: 'active',
    limitPerMonth: 25,
    usage: 7.5,
    usagePercent: 30.0,
    resetInDays: 19,
    createdAt: '15 Jun 2025',
    createdTime: '11:30',
  },
  {
    id: '18',
    provider: 'OpenAI',
    providerIcon: '🟢',
    name: 'OpenAI - Enterprise',
    keyMasked: 'sk-oai-**********5z6',
    model: 'GPT-4o',
    status: 'active',
    limitPerMonth: 500,
    usage: 284.0,
    usagePercent: 56.8,
    resetInDays: 7,
    createdAt: '18 Jun 2025',
    createdTime: '08:45',
  },
]

export function fetchApiKeys(): Promise<ApiKey[]> {
  return Promise.resolve([...API_KEYS])
}
